/*
 * Copyright 2020 The Matrix.org Foundation C.I.C.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.matrix.android.sdk.api.util

import org.matrix.android.sdk.api.extensions.orFalse
import java.util.Locale

// The Android SDK does not provide constant for mime type, add some of them here
object MimeTypes {
    const val Any: String = "*/*"
    const val OctetStream = "application/octet-stream"
    const val Apk = "application/vnd.android.package-archive"

    const val Images = "image/*"

    const val Png = "image/png"
    const val BadJpg = "image/jpg"
    const val Jpeg = "image/jpeg"
    const val Gif = "image/gif"
    const val Webp = "image/webp"

    const val Ogg = "audio/ogg"

    const val PlainText = "text/plain"

    fun String?.normalizeMimeType() = if (this == BadJpg) Jpeg else this

    fun String?.isMimeTypeImage() = this?.startsWith("image/").orFalse()
    fun String?.isMimeTypeVideo() = this?.startsWith("video/").orFalse()
    fun String?.isMimeTypeAudio() = this?.startsWith("audio/").orFalse()
    fun String?.isMimeTypeApplication() = this?.startsWith("application/").orFalse()
    fun String?.isMimeTypeFile() = this?.startsWith("file/").orFalse()
    fun String?.isMimeTypeText() = this?.startsWith("text/").orFalse()
    fun String?.isMimeTypeAny() = this?.startsWith("*/").orFalse()
}

fun String.toMimeType(): String {
    var type = "*/*"
    val doIndex: Int = lastIndexOf(".")
    if (doIndex < 0) {
        return type
    }

    val suffix: String = substring(doIndex + 1).lowercase(Locale.getDefault())
    if (suffix.isEmpty()) {
        return type
    }

    for ((key, value) in MIME_MAP_TABLE) {
        if (suffix == value) {
            type = key
            break
        }
    }
    return type
}


val MIME_MAP_TABLE = mapOf(
    Pair("application/andrew-inset", "ez"),
    Pair("application/dsptype", "tsp"),
    Pair("application/futuresplash", "spl"),
    Pair("application/hta", "hta"),
    Pair("application/mac-binhex40", "hqx"),
    Pair("application/mac-compactpro", "cpt"),
    Pair("application/mathematica", "nb"),
    Pair("application/msaccess", "mdb"),
    Pair("application/oda", "oda"),
    Pair("application/ogg", "ogg"),
    Pair("application/pdf", "pdf"),
    Pair("application/pgp-keys", "key"),
    Pair("application/pgp-signature", "pgp"),
    Pair("application/pics-rules", "prf"),
    Pair("application/rar", "rar"),
    Pair("application/rdf+xml", "rdf"),
    Pair("application/rss+xml", "rss"),
    Pair("application/zip", "zip"),
    Pair("application/vnd.android.package-archive", "apk"),
    Pair("application/vnd.cinderella", "cdy"),
    Pair("application/vnd.ms-pki.stl", "stl"),
    Pair("application/vnd.oasis.opendocument.database", "odb"),
    Pair("application/vnd.oasis.opendocument.formula", "odf"),
    Pair("application/vnd.oasis.opendocument.graphics", "odg"),
    Pair("application/vnd.oasis.opendocument.graphics-template", "otg"),
    Pair("application/vnd.oasis.opendocument.image", "odi"),
    Pair("application/vnd.oasis.opendocument.spreadsheet", "ods"),
    Pair("application/vnd.oasis.opendocument.spreadsheet-template", "ots"),
    Pair("application/vnd.oasis.opendocument.text", "odt"),
    Pair("application/vnd.oasis.opendocument.text-master", "odm"),
    Pair("application/vnd.oasis.opendocument.text-template", "ott"),
    Pair("application/vnd.oasis.opendocument.text-web", "oth"),
    Pair("application/vnd.google-earth.kml+xml", "kml"),
    Pair("application/vnd.google-earth.kmz", "kmz"),
    Pair("application/msword", "doc"),
    Pair("application/msword", "dot"),
    Pair("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx"),
    Pair("application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx"),
    Pair("application/vnd.ms-excel", "xls"),
    Pair("application/vnd.ms-excel", "xlt"),
    Pair("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
    Pair("application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx"),
    Pair("application/vnd.ms-powerpoint", "ppt"),
    Pair("application/vnd.ms-powerpoint", "pot"),
    Pair("application/vnd.ms-powerpoint", "pps"),
    Pair("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx"),
    Pair("application/vnd.openxmlformats-officedocument.presentationml.template", "potx"),
    Pair("application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx"),
    Pair("application/vnd.rim.cod", "cod"),
    Pair("application/vnd.smaf", "mmf"),
    Pair("application/vnd.stardivision.calc", "sdc"),
    Pair("application/vnd.stardivision.draw", "sda"),
    Pair("application/vnd.stardivision.impress", "sdd"),
    Pair("application/vnd.stardivision.impress", "sdp"),
    Pair("application/vnd.stardivision.math", "smf"),
    Pair("application/vnd.stardivision.writer", "sdw"),
    Pair("application/vnd.stardivision.writer", "vor"),
    Pair("application/vnd.stardivision.writer-global", "sgl"),
    Pair("application/vnd.sun.xml.calc", "sxc"),
    Pair("application/vnd.sun.xml.calc.template", "stc"),
    Pair("application/vnd.sun.xml.draw", "sxd"),
    Pair("application/vnd.sun.xml.draw.template", "std"),
    Pair("application/vnd.sun.xml.impress", "sxi"),
    Pair("application/vnd.sun.xml.impress.template", "sti"),
    Pair("application/vnd.sun.xml.math", "sxm"),
    Pair("application/vnd.sun.xml.writer", "sxw"),
    Pair("application/vnd.sun.xml.writer.global", "sxg"),
    Pair("application/vnd.sun.xml.writer.template", "stw"),
    Pair("application/vnd.visio", "vsd"),
    Pair("application/x-abiword", "abw"),
    Pair("application/x-apple-diskimage", "dmg"),
    Pair("application/x-bcpio", "bcpio"),
    Pair("application/x-bittorrent", "torrent"),
    Pair("application/x-cdf", "cdf"),
    Pair("application/x-cdlink", "vcd"),
    Pair("application/x-chess-pgn", "pgn"),
    Pair("application/x-cpio", "cpio"),
    Pair("application/x-debian-package", "deb"),
    Pair("application/x-debian-package", "udeb"),
    Pair("application/x-director", "dcr"),
    Pair("application/x-director", "dir"),
    Pair("application/x-director", "dxr"),
    Pair("application/x-dms", "dms"),
    Pair("application/x-doom", "wad"),
    Pair("application/x-dvi", "dvi"),
    Pair("application/x-flac", "flac"),
    Pair("application/x-font", "pfa"),
    Pair("application/x-font", "pfb"),
    Pair("application/x-font", "gsf"),
    Pair("application/x-font", "pcf"),
    Pair("application/x-font", "pcf.Z"),
    Pair("application/x-freemind", "mm"),
    Pair("application/x-futuresplash", "spl"),
    Pair("application/x-gnumeric", "gnumeric"),
    Pair("application/x-go-sgf", "sgf"),
    Pair("application/x-graphing-calculator", "gcf"),
    Pair("application/x-gtar", "tgz"),
    Pair("application/x-gtar", "gtar"),
    Pair("application/x-gtar", "taz"),
    Pair("application/x-hdf", "hdf"),
    Pair("application/x-ica", "ica"),
    Pair("application/x-internet-signup", "ins"),
    Pair("application/x-internet-signup", "isp"),
    Pair("application/x-iphone", "iii"),
    Pair("application/x-iso9660-image", "iso"),
    Pair("application/x-jmol", "jmz"),
    Pair("application/x-kchart", "chrt"),
    Pair("application/x-killustrator", "kil"),
    Pair("application/x-koan", "skp"),
    Pair("application/x-koan", "skd"),
    Pair("application/x-koan", "skt"),
    Pair("application/x-koan", "skm"),
    Pair("application/x-kpresenter", "kpr"),
    Pair("application/x-kpresenter", "kpt"),
    Pair("application/x-kspread", "ksp"),
    Pair("application/x-kword", "kwd"),
    Pair("application/x-kword", "kwt"),
    Pair("application/x-latex", "latex"),
    Pair("application/x-lha", "lha"),
    Pair("application/x-lzh", "lzh"),
    Pair("application/x-lzx", "lzx"),
    Pair("application/x-maker", "frm"),
    Pair("application/x-maker", "maker"),
    Pair("application/x-maker", "frame"),
    Pair("application/x-maker", "fb"),
    Pair("application/x-maker", "book"),
    Pair("application/x-maker", "fbdoc"),
    Pair("application/x-mif", "mif"),
    Pair("application/x-ms-wmd", "wmd"),
    Pair("application/x-ms-wmz", "wmz"),
    Pair("application/x-msi", "msi"),
    Pair("application/x-ns-proxy-autoconfig", "pac"),
    Pair("application/x-nwc", "nwc"),
    Pair("application/x-object", "o"),
    Pair("application/x-oz-application", "oza"),
    Pair("application/x-pkcs12", "p12"),
    Pair("application/x-pkcs12", "pfx"),
    Pair("application/x-pkcs7-certreqresp", "p7r"),
    Pair("application/x-pkcs7-crl", "crl"),
    Pair("application/x-quicktimeplayer", "qtl"),
    Pair("application/x-shar", "shar"),
    Pair("application/x-shockwave-flash", "swf"),
    Pair("application/x-stuffit", "sit"),
    Pair("application/x-sv4cpio", "sv4cpio"),
    Pair("application/x-sv4crc", "sv4crc"),
    Pair("application/x-tar", "tar"),
    Pair("application/x-texinfo", "texinfo"),
    Pair("application/x-texinfo", "texi"),
    Pair("application/x-troff", "t"),
    Pair("application/x-troff", "roff"),
    Pair("application/x-troff-man", "man"),
    Pair("application/x-ustar", "ustar"),
    Pair("application/x-wais-source", "src"),
    Pair("application/x-wingz", "wz"),
    Pair("application/x-webarchive", "webarchive"),
    Pair("application/x-webarchive-xml", "webarchivexml"),
    Pair("application/x-x509-ca-cert", "crt"),
    Pair("application/x-x509-user-cert", "crt"),
    Pair("application/x-xcf", "xcf"),
    Pair("application/x-xfig", "fig"),
    Pair("application/xhtml+xml", "xhtml"),
    Pair("audio/3gpp", "3gpp"),
    Pair("audio/amr", "amr"),
    Pair("audio/basic", "snd"),
    Pair("audio/midi", "mid"),
    Pair("audio/midi", "midi"),
    Pair("audio/midi", "kar"),
    Pair("audio/midi", "xmf"),
    Pair("audio/mobile-xmf", "mxmf"),
    Pair("audio/mpeg", "mp3"),
    Pair("audio/*", "ape"),
    Pair("audio/*", "flac"),
    Pair("audio/*", "aac"),
    Pair("audio/*", "mpga"),
    Pair("audio/*", "mpega"),
    Pair("audio/*", "mp2"),
    Pair("audio/*", "m4a"),
    Pair("audio/mpegurl", "m3u"),
    Pair("audio/prs.sid", "sid"),
    Pair("audio/x-aiff", "aif"),
    Pair("audio/x-aiff", "aiff"),
    Pair("audio/x-aiff", "aifc"),
    Pair("audio/x-gsm", "gsm"),
    Pair("audio/x-mpegurl", "m3u"),
    Pair("audio/x-ms-wma", "wma"),
    Pair("audio/x-ms-wax", "wax"),
    Pair("audio/x-pn-realaudio", "ra"),
    Pair("audio/x-pn-realaudio", "rm"),
    Pair("audio/x-pn-realaudio", "ram"),
    Pair("audio/x-realaudio", "ra"),
    Pair("audio/x-scpls", "pls"),
    Pair("audio/x-sd2", "sd2"),
    Pair("audio/x-wav", "wav"),
    Pair("audio/mgg", "mgg"),

    Pair("image/bmp", "bmp"),
    Pair("image/gif", "gif"),
    Pair("image/ico", "cur"),
    Pair("image/ico", "ico"),
    Pair("image/ief", "ief"),
    Pair("image/jpeg", "jpeg"),
    Pair("image/jpg", "jpg"),
    Pair("image/jpeg", "jpe"),
    Pair("image/pcx", "pcx"),
    Pair("image/png", "png"),
    Pair("image/svg+xml", "svg"),
    Pair("image/svg+xml", "svgz"),
    Pair("image/tiff", "tiff"),
    Pair("image/tiff", "tif"),
    Pair("image/vnd.djvu", "djvu"),
    Pair("image/vnd.djvu", "djv"),
    Pair("image/vnd.wap.wbmp", "wbmp"),
    Pair("image/x-cmu-raster", "ras"),
    Pair("image/x-coreldraw", "cdr"),
    Pair("image/x-coreldrawpattern", "pat"),
    Pair("image/x-coreldrawtemplate", "cdt"),
    Pair("image/x-corelphotopaint", "cpt"),
    Pair("image/x-icon", "ico"),
    Pair("image/x-jg", "art"),
    Pair("image/x-jng", "jng"),
    Pair("image/x-ms-bmp", "bmp"),
    Pair("image/x-photoshop", "psd"),
    Pair("image/x-portable-anymap", "pnm"),
    Pair("image/x-portable-bitmap", "pbm"),
    Pair("image/x-portable-graymap", "pgm"),
    Pair("image/x-portable-pixmap", "ppm"),
    Pair("image/x-rgb", "rgb"),
    Pair("image/x-xbitmap", "xbm"),
    Pair("image/x-xpixmap", "xpm"),
    Pair("image/x-xwindowdump", "xwd"),
    Pair("image/webp", "webp"),

    Pair("model/iges", "igs"),
    Pair("model/iges", "iges"),
    Pair("model/mesh", "msh"),
    Pair("model/mesh", "mesh"),
    Pair("model/mesh", "silo"),

    Pair("text/calendar", "ics"),
    Pair("text/calendar", "icz"),
    Pair("text/comma-separated-values", "csv"),
    Pair("text/css", "css"),
    Pair("text/html", "htm"),
    Pair("text/html", "html"),
    Pair("text/h323", "323"),
    Pair("text/iuls", "uls"),
    Pair("text/mathml", "mml"),
    Pair("text/plain", "txt"),
    Pair("text/plain", "asc"),
    Pair("text/plain", "text"),
    Pair("text/plain", "diff"),
    Pair("text/plain", "po"),
    Pair("text/richtext", "rtx"),
    Pair("text/rtf", "rtf"),
    Pair("text/texmacs", "ts"),
    Pair("text/text", "phps"),
    Pair("text/tab-separated-values", "tsv"),
    Pair("text/xml", "xml"),
    Pair("text/x-bibtex", "bib"),
    Pair("text/x-boo", "boo"),
    Pair("text/x-c++hdr", "hpp"),
    Pair("text/x-c++hdr", "h++"),
    Pair("text/x-c++hdr", "hxx"),
    Pair("text/x-c++hdr", "hh"),
    Pair("text/x-c++src", "cpp"),
    Pair("text/x-c++src", "c++"),
    Pair("text/x-c++src", "cc"),
    Pair("text/x-c++src", "cxx"),
    Pair("text/x-chdr", "h"),
    Pair("text/x-component", "htc"),
    Pair("text/x-csh", "csh"),
    Pair("text/x-csrc", "c"),
    Pair("text/x-dsrc", "d"),
    Pair("text/x-haskell", "hs"),
    Pair("text/x-java", "java"),
    Pair("text/x-literate-haskell", "lhs"),
    Pair("text/x-moc", "moc"),
    Pair("text/x-pascal", "p"),
    Pair("text/x-pascal", "pas"),
    Pair("text/x-pcs-gcd", "gcd"),
    Pair("text/x-setext", "etx"),
    Pair("text/x-tcl", "tcl"),
    Pair("text/x-tex", "tex"),
    Pair("text/x-tex", "ltx"),
    Pair("text/x-tex", "sty"),
    Pair("text/x-tex", "cls"),
    Pair("text/x-vcalendar", "vcs"),
    Pair("text/x-vcard", "vcf"),
    Pair("video/3gpp", "3gpp"),
    Pair("video/3gpp", "3gp"),
    Pair("video/3gpp", "3g2"),
    Pair("video/dl", "dl"),
    Pair("video/dv", "dif"),
    Pair("video/dv", "dv"),
    Pair("video/fli", "fli"),
    Pair("video/m4v", "m4v"),
    Pair("video/mpeg", "mpeg"),
    Pair("video/mpeg", "mpg"),
    Pair("video/mpeg", "mpe"),
    Pair("video/mp4", "mp4"),
    Pair("video/*", "rmvb"),
    Pair("video/*", "flv"),
    Pair("video/*", "mkv"),
    Pair("video/*", "ts"),
    Pair("video/mpeg", "VOB"),
    Pair("video/quicktime", "qt"),
    Pair("video/quicktime", "mov"),
    Pair("video/vnd.mpegurl", "mxu"),
    Pair("video/x-la-asf", "lsf"),
    Pair("video/x-la-asf", "lsx"),
    Pair("video/x-mng", "mng"),
    Pair("video/x-ms-asf", "asf"),
    Pair("video/x-ms-asf", "asx"),
    Pair("video/x-ms-wm", "wm"),
    Pair("video/x-ms-wmv", "wmv"),
    Pair("video/x-ms-wmx", "wmx"),
    Pair("video/x-ms-wvx", "wvx"),
    Pair("video/x-msvideo", "avi"),
    Pair("video/x-sgi-movie", "movie"),
    Pair("video/x-webex", "wrf"),
    Pair("x-conference/x-cooltalk", "ice"),
    Pair("x-epoc/x-sisx-app", "sisx"),
    Pair("image/*", "3fr"),
    Pair("image/*", "arw"),
    Pair("image/*", "avs"),
    Pair("image/*", "cals"),
    Pair("image/*", "cr2"),
    Pair("image/*", "crw"),
    Pair("image/*", "cut"),
    Pair("image/*", "dcm"),
    Pair("image/*", "dcx"),
    Pair("image/*", "dib"),
    Pair("image/*", "dng"),
    Pair("image/*", "dpx"),
    Pair("image/*", "emf"),
    Pair("image/*", "emz"),
    Pair("image/*", "eps"),
    Pair("image/*", "erf"),
    Pair("image/*", "fax"),
    Pair("image/*", "fits"),
    Pair("image/*", "fpx"),
    Pair("image/*", "heic"),
    Pair("image/*", "ithmb"),
    Pair("image/*", "j2c"),
    Pair("image/*", "j2k"),
    Pair("image/*", "jbig"),
    Pair("image/*", "jp2"),
    Pair("image/*", "jpc"),
    Pair("image/*", "kdc"),
    Pair("image/*", "mat"),
    Pair("image/*", "mef"),
    Pair("image/*", "miff"),
    Pair("image/*", "mos"),
    Pair("image/*", "mrw"),
    Pair("image/*", "mtv"),
    Pair("image/*", "mvg"),
    Pair("image/*", "nef"),
    Pair("image/*", "nrw"),
    Pair("image/*", "orf"),
    Pair("image/*", "otb"),
    Pair("image/*", "p7"),
    Pair("image/*", "palm"),
    Pair("image/*", "pam"),
    Pair("image/*", "pcd"),
    Pair("image/*", "pcds"),
    Pair("image/*", "pef"),
    Pair("image/*", "picon"),
    Pair("image/*", "pict"),
    Pair("image/*", "pix"),
    Pair("image/*", "ptif"),
    Pair("image/*", "raf"),
    Pair("image/*", "raw"),
    Pair("image/*", "rla"),
    Pair("image/*", "rle"),
    Pair("image/*", "rw2"),
    Pair("image/*", "sct"),
    Pair("image/*", "sfw"),
    Pair("image/*", "sgi"),
    Pair("image/*", "sr2"),
    Pair("image/*", "srf"),
    Pair("image/*", "sun"),
    Pair("image/*", "tga"),
    Pair("image/*", "thm"),
    Pair("image/*", "tim"),
    Pair("image/*", "vicar"),
    Pair("image/*", "viff"),
    Pair("image/*", "wmf"),
    Pair("image/*", "wpg"),
    Pair("image/*", "x3f"),
    Pair("image/*", "xv"),
    Pair("video/*", "261"),
    Pair("video/*", "4xm"),
    Pair("video/*", "anm"),
    Pair("video/*", "bfi"),
    Pair("video/*", "bmv"),
    Pair("video/*", "c93"),
    Pair("video/*", "cdg"),
    Pair("video/*", "cdxl"),
    Pair("video/*", "cin"),
    Pair("video/*", "dfa"),
    Pair("video/*", "drc"),
    Pair("video/*", "dxa"),
    Pair("video/*", "f4v"),
    Pair("video/*", "gxf"),
    Pair("video/*", "h261"),
    Pair("video/*", "h263"),
    Pair("video/*", "h264"),
    Pair("video/*", "ivf"),
    Pair("video/*", "lvf"),
    Pair("video/*", "mj2"),
    Pair("video/*", "mjpeg"),
    Pair("video/*", "mtv"),
    Pair("video/*", "mv"),
    Pair("video/*", "mvi"),
    Pair("video/*", "mxf"),
    Pair("video/*", "mxg"),
    Pair("video/*", "nsv"),
    Pair("video/*", "nut"),
    Pair("video/*", "nuv"),
    Pair("video/*", "p64"),
    Pair("video/*", "paf"),
    Pair("video/*", "pmp"),
    Pair("video/*", "pva"),
    Pair("video/*", "rl2"),
    Pair("video/*", "roq"),
    Pair("video/*", "rpl"),
    Pair("video/*", "smk"),
    Pair("video/*", "thp"),
    Pair("video/*", "txd"),
    Pair("video/*", "vc1"),
    Pair("video/*", "viv"),
    Pair("video/*", "vivo"),
    Pair("video/*", "vmd"),
    Pair("video/*", "vob"),
    Pair("video/*", "webm"),
    Pair("video/*", "wtv"),
    Pair("video/*", "xmv"),
    Pair("video/*", "yop"),
    Pair("video/*", "3gp2"),
    Pair("video/*", "amv"),
    Pair("video/*", "divx"),
    Pair("video/*", "gvi"),
    Pair("video/*", "ismv"),
    Pair("video/*", "m1v"),
    Pair("video/*", "m2v"),
    Pair("video/*", "m2t"),
    Pair("video/*", "m2ts"),
    Pair("video/*", "m3u8"),
    Pair("video/*", "mp2v"),
    Pair("video/*", "mp4v"),
    Pair("video/*", "mpeg1"),
    Pair("video/*", "mpeg2"),
    Pair("video/*", "mpeg4"),
    Pair("video/*", "mpv2"),
    Pair("video/*", "mts"),
    Pair("video/*", "ogm"),
    Pair("video/*", "ogv"),
    Pair("video/*", "ogx"),
    Pair("video/*", "ps"),
    Pair("video/*", "rec"),
    Pair("video/*", "tod"),
    Pair("video/*", "trp"),
    Pair("video/*", "tts"),
    Pair("video/*", "vro"),
    Pair("video/*", "xesc"),
    Pair("audio/*", "ac3"),
    Pair("audio/*", "act"),
    Pair("audio/*", "adts"),
    Pair("audio/*", "aea"),
    Pair("audio/*", "apc"),
    Pair("audio/*", "au"),
    Pair("audio/*", "caf"),
    Pair("audio/*", "dts"),
    Pair("audio/*", "eac3"),
    Pair("audio/*", "g722"),
    Pair("audio/*", "iff"),
    Pair("audio/*", "ircam"),
    Pair("audio/*", "iss"),
    Pair("audio/*", "mlp"),
    Pair("audio/*", "mpc"),
    Pair("audio/*", "oma"),
    Pair("audio/*", "pvf"),
    Pair("audio/*", "qcp"),
    Pair("audio/*", "rso"),
    Pair("audio/*", "sbg"),
    Pair("audio/*", "shn"),
    Pair("audio/*", "sol"),
    Pair("audio/*", "tta"),
    Pair("audio/*", "voc"),
    Pair("audio/*", "vqf"),
    Pair("audio/*", "w64"),
    Pair("audio/*", "wv"),
    Pair("audio/*", "xa"),
    Pair("audio/*", "xwma"),
    Pair("audio/*", "3ga"),
    Pair("audio/*", "a52"),
    Pair("audio/*", "adt"),
    Pair("audio/*", "aob"),
    Pair("audio/*", "awb"),
    Pair("audio/*", "it"),
    Pair("audio/*", "m4b"),
    Pair("audio/*", "m4p"),
    Pair("audio/*", "mka"),
    Pair("audio/*", "mod"),
    Pair("audio/*", "mpa"),
    Pair("audio/*", "mp1"),
    Pair("audio/*", "oga"),
    Pair("audio/*", "opus"),
    Pair("audio/*", "rmi"),
    Pair("audio/*", "s3m"),
    Pair("audio/*", "spx"),
    Pair("audio/*", "xm"),
    Pair("audio/*", "3ga"),
    Pair("audio/*", "a52"),
    Pair("audio/*", "adt"),
    Pair("audio/*", "aob"),
    Pair("audio/*", "awb"),
    Pair("audio/*", "it"),
    Pair("audio/*", "m4b"),
    Pair("audio/*", "m4p"),
    Pair("audio/*", "mka"),
    Pair("audio/*", "mod"),
    Pair("audio/*", "mpa"),
    Pair("audio/*", "mp1"),
    Pair("audio/*", "oga"),
    Pair("audio/*", "opus"),
    Pair("audio/*", "rmi"),
    Pair("audio/*", "s3m"),
    Pair("audio/*", "spx"),
    Pair("audio/*", "xm"),
    Pair("text/plain", "adb"),
    Pair("text/plain", "ads"),
    Pair("text/plain", "asa"),
    Pair("text/plain", "asax"),
    Pair("text/plain", "asm"),
    Pair("text/plain", "asp"),
    Pair("text/plain", "aspx"),
    Pair("text/plain", "au3"),
    Pair("text/plain", "aut"),
    Pair("text/plain", "bas"),
    Pair("text/plain", "bat"),
    Pair("text/plain", "bc"),
    Pair("text/plain", "bluebutton"),
    Pair("text/plain", "bsh"),
    Pair("text/plain", "cfg"),
    Pair("text/plain", "cgi"),
    Pair("text/plain", "cln"),
    Pair("text/plain", "cmake"),
    Pair("text/plain", "cnf"),
    Pair("text/plain", "conf"),
    Pair("text/plain", "cs"),
    Pair("text/plain", "csproj"),
    Pair("text/plain", "ctest"),
    Pair("text/plain", "ctl"),
    Pair("text/plain", "def"),
    Pair("text/plain", "dfm"),
    Pair("text/plain", "diz"),
    Pair("text/plain", "dlg"),
    Pair("text/plain", "dob"),
    Pair("text/plain", "docbook"),
    Pair("text/plain", "dpk"),
    Pair("text/plain", "dpr"),
    Pair("text/plain", "dsm"),
    Pair("text/plain", "dsr"),
    Pair("text/plain", "e"),
    Pair("text/plain", "erb"),
    Pair("text/plain", "erl"),
    Pair("text/plain", "es"),
    Pair("text/plain", "exp"),
    Pair("text/plain", "f"),
    Pair("text/plain", "f2k"),
    Pair("text/plain", "f90"),
    Pair("text/plain", "f95"),
    Pair("text/plain", "for"),
    Pair("text/plain", "g"),
    Pair("text/plain", "gd"),
    Pair("text/plain", "gi"),
    Pair("text/plain", "hrl"),
    Pair("text/plain", "htaccess"),
    Pair("text/plain", "htd"),
    Pair("text/plain", "idl"),
    Pair("text/plain", "iface"),
    Pair("text/plain", "impl"),
    Pair("text/plain", "inc"),
    Pair("text/plain", "inf"),
    Pair("text/plain", "ini"),
    Pair("text/plain", "ipp"),
    Pair("text/plain", "isl"),
    Pair("text/plain", "iss"),
    Pair("text/plain", "js"),
    Pair("text/plain", "jsp"),
    Pair("text/plain", "ksh"),
    Pair("text/plain", "log"),
    Pair("text/plain", "lst"),
    Pair("text/plain", "lua"),
    Pair("text/plain", "m"),
    Pair("text/plain", "mak"),
    Pair("text/plain", "manifest"),
    Pair("text/plain", "ml"),
    Pair("text/plain", "mli"),
    Pair("text/plain", "mp"),
    Pair("text/plain", "mpx"),
    Pair("text/plain", "nfo"),
    Pair("text/plain", "nsh"),
    Pair("text/plain", "nsi"),
    Pair("text/plain", "odl"),
    Pair("text/plain", "pag"),
    Pair("text/plain", "php"),
    Pair("text/plain", "php3"),
    Pair("text/plain", "phtml"),
    Pair("text/plain", "pl"),
    Pair("text/plain", "pm"),
    Pair("text/plain", "pod"),
    Pair("text/plain", "pov"),
    Pair("text/plain", "pp"),
    Pair("text/plain", "properties"),
    Pair("text/plain", "py"),
    Pair("text/plain", "pyw"),
    Pair("text/plain", "r"),
    Pair("text/plain", "rake"),
    Pair("text/plain", "rb"),
    Pair("text/plain", "rbw"),
    Pair("text/plain", "rc"),
    Pair("text/plain", "rc2"),
    Pair("text/plain", "reg"),
    Pair("text/plain", "rhtml"),
    Pair("text/plain", "rjs"),
    Pair("text/plain", "rsource"),
    Pair("text/plain", "s"),
    Pair("text/plain", "session"),
    Pair("text/plain", "sh"),
    Pair("text/plain", "shtml"),
    Pair("text/plain", "sign"),
    Pair("text/plain", "sma"),
    Pair("text/plain", "stm"),
    Pair("text/plain", "tab"),
    Pair("text/plain", "url"),
    Pair("text/plain", "v"),
    Pair("text/plain", "vala"),
    Pair("text/plain", "vb"),
    Pair("text/plain", "vbg"),
    Pair("text/plain", "vbp"),
    Pair("text/plain", "vbproj"),
    Pair("text/plain", "vbs"),
    Pair("text/plain", "vbw"),
    Pair("text/plain", "vh"),
    Pair("text/plain", "vhd"),
    Pair("text/plain", "vhdl"),
    Pair("text/plain", "xaml"),
    Pair("text/plain", "xmp"),
    Pair("text/plain", "yaml"),
    Pair("text/plain", "yml"),
    Pair("text/plain", "xls") //            ,{"text/plain", "pptx"},
    //            {"text/plain", "xlsx"},
    //            {"text/plain", "pdf"},
    //            {"text/plain", "docx"}

)
